language: node_js
node_js:
  - "4.2.6"
  - "5.5.0"
addons:
  postgresql: 9.4
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8